### ISSUE TITLE
Release of semantic segmentation code?

### ISSUE THREAD

**Issue by Siddharth-Shrivastava7** [fudan-zvg/meta-prompts#1]
Hi @wwqq,  

Congrats for the great work! 
I want to know when you will open source the code for semantic segmentation? 

Thanks!

**Comment by wwqq** [comment]
Hi @Siddharth-Shrivastava7, We are organizing the code and preparing the finetuned models, we expect to release the code and model by the end of January.

**Comment by Siddharth-Shrivastava7** [comment]
Alright, great to know! 
And, thanks for the quick response!
